import gen_purchase_order
import edi_document
import crm_helpdesk
import wizard
import thr_combined
import thr_masterdata
import thr_masterdata_categories
import thr_masterdata_properties
import thr_masterdata_products
import thr_pricing
import thr_availability
import settings
import spree_sale_order
import spree_product_manager
import spree_shipment_manager
import post_install